language: ruby
notifications:
  email:
    on_success: change
    on_failure: always
rvm:
  - 1.8.7
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  #- jruby-head
  #- ruby-head
  - ree
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - bundle --version
  - mkdir -p tmp/bundle

gemfile:
  - rails2_3.gemfile
  - rails3_0.gemfile
  - rails3_1.gemfile
  - rails3_2.gemfile
  #- rails_edge.gemfile

bundler_args: "--binstubs"

script: ./test/test_with_railsapp

matrix:
  exclude:
    - rvm: rbx-18mode
      gemfile: rails2_3.gemfile
    - rvm: rbx-19mode
      gemfile: rails2_3.gemfile
    - rvm: jruby-18mode
      gemfile: rails2_3.gemfile
    - rvm: jruby-19mode
      gemfile: rails2_3.gemfile
    - rvm: jruby-head
      gemfile: rails2_3.gemfile
    - rvm: ruby-head
      gemfile: rails2_3.gemfile
    - rvm: 1.9.3
      gemfile: rails2_3.gemfile

    - rvm: 1.8.7
      gemfile: rails_edge.gemfile
    - rvm: rbx-18mode
      gemfile: rails_edge.gemfile
    - rvm: jruby-18mode
      gemfile: rails_edge.gemfile
    - rvm: ree
      gemfile: rails_edge.gemfile
  allow_failures:
    - gemfile: rails_edge.gemfile
    - rvm: jruby-head
    - rvm: ruby-head
