language: ruby
notifications:
  email:
    on_success: change
    on_failure: always
rvm:
  - 1.8.7
  - 1.9.3
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - bundle --version
  - mkdir -p tmp/bundle

gemfile:
  - gemfiles/rails2_3.gemfile
  - gemfiles/rails3_0.gemfile
  - gemfiles/rails3_1.gemfile
  - gemfiles/rails3_2.gemfile
  - gemfiles/rails_edge.gemfile

script: ./test/test_with_railsapp

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails2_3.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_edge.gemfile
