language: ruby
notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - gem install bundler
  - bundle --version
  - mkdir -p tmp/bundle

bundler_args: "--binstubs"

script: ./test/test_with_railsapp

matrix:
  allow_failures:
    - rvm: ruby-head
      gemfile: test/rails_edge.gemfile
      env: RAILS_VERSION=edge

    - rvm: ruby-head
      gemfile: test/rails_5.0.gemfile
      env: RAILS_VERSION=5.0

  include:
    # ruby / rails edge
    
    - rvm: ruby-head
      gemfile: test/rails_edge.gemfile
      env: RAILS_VERSION=edge

    # ruby 5.0  Jun. 2016
    
    - rvm: 2.2.2
      gemfile: test/rails_5.0.gemfile
      env: RAILS_VERSION=5.0

    - rvm: ruby-head
      gemfile: test/rails_5.0.gemfile
      env: RAILS_VERSION=5.0

