language: ruby
rvm:
  - 1.8.7
  - 1.9.3
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - bundle --version
  - mkdir -p tmp/bundle

gemfile:
  - gemfiles/rails2_3.gemfile

script: ./test/test_with_railsapp

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails2_3.gemfile
